import fspromises from "fs/promises";
import {ASSETS_ROOT_DIR} from "../data/constants";

const freeAvatars = [
    "free/Barbarian__King_info.webp",
    "free/BULGUYHAIR.webp",
    "free/default.webp",
    "free/free_skull.webp",
    "free/spray_bull.webp",
    "free/spray_cross.webp",
    "free/spray_denied.webp",
    "free/spray_starrpark.webp",
    "free/thumbs_down.webp",
    "free/yellow_face.webp"
];
const specialAvatars = [
    "special/angry_darryl.webp",
    "special/ash_special_01.webp",
    "special/brawlbox_icon.webp",
    "special/bush.webp",
    "special/collection_01.webp",
    "special/collection_02.webp",
    "special/collection_03.webp",
    "special/collection_04.webp",
    "special/collection_05.webp",
    "special/collection_06.webp",
    "special/collection_07.webp",
    "special/collection_08.webp",
    "special/darryl_special_01.webp",
    "special/elprimo_special_01.webp",
    "special/elprimo_special_02.webp",
    "special/gamemode_bounty.webp",
    "special/gamemode_brawlball.webp",
    "special/gamemode_gemgrab.webp",
    "special/gamemode_heist.webp",
    "special/gem.webp",
    "special/portrait_8bit.webp",
    "special/portrait_amber.webp",
    "special/portrait_ash.webp",
    "special/portrait_barley.webp",
    "special/portrait_bea.webp",
    "special/portrait_belle.webp",
    "special/portrait_bibi.webp",
    "special/portrait_bo.webp",
    "special/portrait_bonnie.webp",
    "special/portrait_brock.webp",
    "special/portrait_bull.webp",
    "special/portrait_buster.webp",
    "special/portrait_buzz.webp",
    "special/portrait_byron.webp",
    "special/portrait_carl.webp",
    "special/portrait_charlie.webp",
    "special/portrait_chester.webp",
    "special/portrait_chuck.webp",
    "special/portrait_colette.webp",
    "special/portrait_colt.webp",
    "special/portrait_cordelius.webp",
    "special/portrait_crow.webp",
    "special/portrait_darryl.webp",
    "special/portrait_doug.webp",
    "special/portrait_dynamike.webp",
    "special/portrait_edgar.webp",
    "special/portrait_elprimo.webp",
    "special/portrait_emz.webp",
    "special/portrait_eve.webp",
    "special/portrait_fang.webp",
    "special/portrait_frank.webp",
    "special/portrait_gale.webp",
    "special/portrait_gene.webp",
    "special/portrait_gray.webp",
    "special/portrait_griff.webp",
    "special/portrait_grom.webp",
    "special/portrait_gus.webp",
    "special/portrait_hank.webp",
    "special/portrait_jacky.webp",
    "special/portrait_janet.webp",
    "special/portrait_jessie.webp",
    "special/portrait_leon.webp",
    "special/portrait_lola.webp",
    "special/portrait_lou.webp",
    "special/portrait_maisie.webp",
    "special/portrait_mandy.webp",
    "special/portrait_max.webp",
    "special/portrait_meg.webp",
    "special/portrait_mortis.webp",
    "special/portrait_mrp.webp",
    "special/portrait_nani.webp",
    "special/portrait_nita.webp",
    "special/portrait_otis.webp",
    "special/portrait_pam.webp",
    "special/portrait_pearl.webp",
    "special/portrait_penny.webp",
    "special/portrait_piper.webp",
    "special/portrait_poco.webp",
    "special/portrait_rico.webp",
    "special/portrait_rosa.webp",
    "special/portrait_rt.webp",
    "special/portrait_ruffs.webp",
    "special/portrait_sam.webp",
    "special/portrait_sandy.webp",
    "special/portrait_shelly.webp",
    "special/portrait_spike.webp",
    "special/portrait_sprout.webp",
    "special/portrait_squeak.webp",
    "special/portrait_stu.webp",
    "special/portrait_surge.webp",
    "special/portrait_tara.webp",
    "special/portrait_tick.webp",
    "special/portrait_willow.webp",
    "special/sadpin.webp",
    "special/space.webp",
    "special/starpoint.webp",
    "special/star_icon.webp",
    "special/STOMPER.webp",
    "special/viking_bull.webp"
];
const freeThemes = [
    "free/default_background.webp",
    "free/default_icon.webp",
    "free/default_music.ogg",
    "free/default_preview.webp",
    "free/default_selectpreview.webp"
];
const specialThemes = [
    "special/darkmas_background.webp",
    "special/darkmas_icon.webp",
    "special/darkmas_music.ogg",
    "special/darkmas_preview.webp",
    "special/darkmas_selectpreview.webp",
    "special/deepsea_background.webp",
    "special/deepsea_icon.webp",
    "special/deepsea_music.ogg",
    "special/deepsea_preview.webp",
    "special/deepsea_selectpreview.webp",
    "special/fairytale_background.webp",
    "special/fairytale_icon.webp",
    "special/fairytale_music.ogg",
    "special/fairytale_preview.webp",
    "special/fairytale_selectpreview.webp",
    "special/giftshop_background.webp",
    "special/giftshop_icon.webp",
    "special/giftshop_music.ogg",
    "special/giftshop_preview.webp",
    "special/giftshop_selectpreview.webp",
    "special/legendaryset_background.webp",
    "special/legendaryset_icon.webp",
    "special/legendaryset_music.ogg",
    "special/legendaryset_preview.webp",
    "special/legendaryset_selectpreview.webp",
    "special/lny_20_background.webp",
    "special/lny_20_icon.webp",
    "special/lny_20_music.ogg",
    "special/lny_20_preview.webp",
    "special/lny_20_selectpreview.webp",
    "special/lunar_background.webp",
    "special/lunar_icon.webp",
    "special/lunar_music.ogg",
    "special/lunar_preview.webp",
    "special/lunar_selectpreview.webp",
    "special/mandy_background.webp",
    "special/mandy_icon.webp",
    "special/mandy_music.ogg",
    "special/mandy_preview.webp",
    "special/mandy_selectpreview.webp",
    "special/mecha_background.webp",
    "special/mecha_icon.webp",
    "special/mecha_music.ogg",
    "special/mecha_preview.webp",
    "special/mecha_selectpreview.webp",
    "special/pirate_background.webp",
    "special/pirate_icon.webp",
    "special/pirate_music.ogg",
    "special/pirate_preview.webp",
    "special/pirate_selectpreview.webp",
    "special/psg_background.webp",
    "special/psg_icon.webp",
    "special/psg_music.ogg",
    "special/psg_preview.webp",
    "special/psg_selectpreview.webp",
    "special/retro_background.webp",
    "special/retro_icon.webp",
    "special/retro_music.ogg",
    "special/retro_preview.webp",
    "special/retro_selectpreview.webp",
    "special/starrforce_background.webp",
    "special/starrforce_icon.webp",
    "special/starrforce_music.ogg",
    "special/starrforce_preview.webp",
    "special/starrforce_selectpreview.webp",
    "special/stuntshow_background.webp",
    "special/stuntshow_icon.webp",
    "special/stuntshow_music.ogg",
    "special/stuntshow_preview.webp",
    "special/stuntshow_selectpreview.webp",
    "special/super_city_background.webp",
    "special/super_city_icon.webp",
    "special/super_city_music.ogg",
    "special/super_city_preview.webp",
    "special/super_city_selectpreview.webp",
    "special/taras_bazaar_background.webp",
    "special/taras_bazaar_icon.webp",
    "special/taras_bazaar_music.ogg",
    "special/taras_bazaar_preview.webp",
    "special/taras_bazaar_selectpreview.webp",
    "special/waterpark_background.webp",
    "special/waterpark_icon.webp",
    "special/waterpark_music.ogg",
    "special/waterpark_preview.webp",
    "special/waterpark_selectpreview.webp",
    "special/yellow_face_background.webp",
    "special/yellow_face_icon.webp",
    "special/yellow_face_music.ogg",
    "special/yellow_face_preview.webp",
    "special/yellow_face_selectpreview.webp"
];
const scenes = [
    "default",
    "arcade_preview.webp",
    "arcade_scene.glb",
    "canyon_preview.webp",
    "canyon_scene.glb",
    "default_preview.webp",
    "giftshop_preview.webp",
    "giftshop_scene.glb",
    "mine_preview.webp",
    "mine_scene.glb",
    "retropolis_preview.webp",
    "retropolis_scene.glb",
    "stunt_show_preview.webp",
    "stunt_show_scene.glb"
];

// Copy all the required directories from KINGS then run these
// functions to obtain the names of the files that exist. Put
// the results of these functions into the arrays above.
export async function readFreeAvatars(): Promise<string[]>{
    return freeAvatars;
    return fspromises.readdir(`${ASSETS_ROOT_DIR}avatars/free`)
    .then((result) => {
        for (let x = 0; x < result.length; x++){
            result[x] = "free/" + result[x];
        }
        console.log(result);
        return result;
    })
    .catch((error) => []);
}

export async function readSpecialAvatars(): Promise<string[]>{
    return specialAvatars;
    return fspromises.readdir(`${ASSETS_ROOT_DIR}avatars/special`)
    .then((result) => {
        for (let x = 0; x < result.length; x++){
            result[x] = "special/" + result[x];
        }
        console.log(result);
        return result;
    })
    .catch((error) => []);
}

export async function readFreeThemes(): Promise<string[]>{
    return freeThemes;
    return fspromises.readdir(`${ASSETS_ROOT_DIR}themes/free`)
    .then((result) => {
        for (let x = 0; x < result.length; x++){
            result[x] = "free/" + result[x];
        }
        console.log(result);
        return result;
    })
    .catch((error) => []);
}

export async function readSpecialThemes(): Promise<string[]>{
    return specialThemes;
    return fspromises.readdir(`${ASSETS_ROOT_DIR}themes/special`)
    .then((result) => {
        for (let x = 0; x < result.length; x++){
            result[x] = "special/" + result[x];
        }
        console.log(result);
        return result;
    })
    .catch((error) => []);
}

export async function readScenes(): Promise<string[]>{
    return scenes;
    return fspromises.readdir(`${ASSETS_ROOT_DIR}scenes`)
    .then((result) => {
        const result2 = ["default"].concat(result);
        console.log(result2);
        return result2;
    })
    .catch((error) => []);
}

// Use this function to get all the model files that exist
async function readModels(): Promise<string[]>{    
    return (await Promise.all<Promise<string[]>>((
        await fspromises.readdir(`${ASSETS_ROOT_DIR}models`)
        .then((result) => result)
        .catch((error) => [] as string[])
    ).map((brawler) => 
        fspromises.readdir(`${ASSETS_ROOT_DIR}models/${brawler}`)
        .then((result) => result.map((file) => `${brawler}/${file}`))
        .catch((error) => [])
    ))).reduce((previousValue, currentValue) => previousValue.concat(currentValue), []);
}
//readModels().then((value) => {for (let x = 0; x < value.length; x++){console.log(`    "${value[x]}"${x < value.length - 1 ? "," : ""}`);}});

export const modelFiles = new Set<string>(([
    "8bit/arcadedefault.glb",
    "8bit/arcaderetropolis.glb",
    "8bit/arcaderetropolis_lose.glb",
    "8bit/arcaderetropolis_win.glb",
    "8bit/arcadevirus.glb",
    "8bit/arcadevirus_lose.glb",
    "8bit/arcadevirus_win.glb",
    "amber/firedudedefault.glb",
    "amber/firedudedefault_lose.glb",
    "amber/firedudedefault_win.glb",
    "amber/firedudefrost.glb",
    "amber/firedudefrost_lose.glb",
    "amber/firedudefrost_win.glb",
    "ash/knightdefault.glb",
    "ash/knightdefault_lose.glb",
    "ash/knightdefault_win.glb",
    "ash/knightkrampus.glb",
    "ash/knightninja.glb",
    "ash/knightninja_lose.glb",
    "ash/knightninja_win.glb",
    "ash/knightpizza.glb",
    "barley/barkeepdefault.glb",
    "barley/barkeepdefault_lose.glb",
    "barley/barkeepdefault_win.glb",
    "bea/beesniperarchvillain.glb",
    "bea/beesniperarchvillain_lose.glb",
    "bea/beesniperarchvillain_win.glb",
    "bea/beesniperdefault.glb",
    "bea/beesniperdefault_lose.glb",
    "bea/beesniperdefault_win.glb",
    "belle/electrosnipercoral.glb",
    "belle/electrosnipercoral_lose.glb",
    "belle/electrosnipercoral_win.glb",
    "belle/electrosniperdefault.glb",
    "belle/electrosniperdefault_lose.glb",
    "belle/electrosniperdefault_win.glb",
    "bibi/baseballdefault.glb",
    "bibi/baseballdefault_lose.glb",
    "bibi/baseballdefault_win.glb",
    "bibi/baseballgamer.glb",
    "bibi/baseballgamer_lose.glb",
    "bibi/baseballgamer_win.glb",
    "bo/bowdudedefault.glb",
    "bo/bowdudedefault_lose.glb",
    "bo/bowdudedefault_win.glb",
    "bonnie/cannongirldefault.glb",
    "bonnie/cannongirldefault_lose.glb",
    "bonnie/cannongirldefault_win.glb",
    "bonnie/cannongirlvillain.glb",
    "bonnie/cannongirlvillain_lose.glb",
    "bonnie/cannongirlvillain_win.glb",
    "brock/rocketgirldefault.glb",
    "bull/bulldudealleycat.glb",
    "bull/bulldudealleycat_lose.glb",
    "bull/bulldudealleycat_win.glb",
    "bull/bulldudebarbking.glb",
    "bull/bulldudebarbking_lose.glb",
    "bull/bulldudebarbking_win.glb",
    "bull/bulldudefootbullblue.glb",
    "bull/bulldudegold.glb",
    "bull/bulldudelion.glb",
    "bull/bulldudemang.glb",
    "bull/bulldudemang_lose.glb",
    "bull/bulldudemang_win.glb",
    "bull/bulldudeox.glb",
    "bull/bulldudeox_lose.glb",
    "bull/bulldudeox_win.glb",
    "bull/bulldudesilver.glb",
    "bull/bulldudeterminator.glb",
    "bull/bullguydefault.glb",
    "bull/bullguydefault_lose.glb",
    "bull/bullguydefault_win.glb",
    "bull/bullguyfootbull.glb",
    "bull/bullguyfootbull_lose.glb",
    "bull/bullguyfootbull_win.glb",
    "bull/bullguyhair.glb",
    "bull/bullguyhair_lose.glb",
    "bull/bullguyhair_win.glb",
    "buster/shieldtankdefault.glb",
    "buster/shieldtankdefault_lose.glb",
    "buster/shieldtankdefault_win.glb",
    "buzz/ropedudedefault.glb",
    "buzz/ropedudedefault_lose.glb",
    "buzz/ropedudedefault_win.glb",
    "byron/snakeoildefault.glb",
    "byron/snakeoildefault_lose.glb",
    "byron/snakeoildefault_win.glb",
    "carl/whirlwinddefault.glb",
    "carl/whirlwindhogrider.glb",
    "carl/whirlwindhogrider_lose.glb",
    "carl/whirlwindhogrider_win.glb",
    "charlie/cocoonerdefault.glb",
    "charlie/cocoonerdefault_lose.glb",
    "charlie/cocoonerdefault_win.glb",
    "chester/jesterdefault.glb",
    "chester/jesterdefault_lose.glb",
    "chester/jesterdefault_win.glb",
    "chuck/conductordefault.glb",
    "chuck/conductordefault_lose.glb",
    "chuck/conductordefault_win.glb",
    "colette/percenterdefault.glb",
    "colette/percenterdefault_lose.glb",
    "colette/percenterdefault_win.glb",
    "colette/percentergladiator.glb",
    "colette/percentergladiator_lose.glb",
    "colette/percentergladiator_win.glb",
    "colette/percenterinspector.glb",
    "colette/percenterinspector_lose.glb",
    "colette/percenterinspector_win.glb",
    "colt/gunslingerdefault.glb",
    "colt/gunslingerdefault_lose.glb",
    "colt/gunslingerdefault_win.glb",
    "colt/gunslingerhanbok.glb",
    "colt/gunslingerhanbok_lose.glb",
    "colt/gunslingerhanbok_win.glb",
    "cordelius/duelistdefault.glb",
    "cordelius/duelistdefault_lose.glb",
    "cordelius/duelistdefault_win.glb",
    "crow/crowdefault.glb",
    "crow/crowdefault_lose.glb",
    "crow/crowdefault_win.glb",
    "crow/crowmechagold.glb",
    "crow/crowmechagold_lose.glb",
    "crow/crowmechagold_win.glb",
    "crow/crowsuper.glb",
    "crow/crowwhite.glb",
    "darryl/barrelbotcny.glb",
    "darryl/barrelbotcny_lose.glb",
    "darryl/barrelbotcny_win.glb",
    "darryl/barrelbotcrash.glb",
    "darryl/barrelbotcrash_lose.glb",
    "darryl/barrelbotcrash_win.glb",
    "darryl/barrelbotdefault.glb",
    "darryl/barrelbotdefault_lose.glb",
    "darryl/barrelbotdefault_win.glb",
    "darryl/barrelbotmegabox.glb",
    "darryl/barrelbotmegabox_lose.glb",
    "darryl/barrelbotmegabox_win.glb",
    "doug/reviverdefault.glb",
    "doug/reviverdefault_lose.glb",
    "doug/reviverdefault_win.glb",
    "dynamike/tntguydefault.glb",
    "dynamike/tntguydefault_lose.glb",
    "dynamike/tntguydefault_win.glb",
    "edgar/enragerdefault.glb",
    "edgar/enragerdefault_lose.glb",
    "edgar/enragerdefault_win.glb",
    "elprimo/luchadoratomic.glb",
    "elprimo/luchadorbrown.glb",
    "elprimo/luchadorbrown_lose.glb",
    "elprimo/luchadorbrown_win.glb",
    "elprimo/luchadorbutler.glb",
    "elprimo/luchadorbutler_lose.glb",
    "elprimo/luchadorbutler_win.glb",
    "elprimo/luchadorcorazon.glb",
    "elprimo/luchadorcorazon_lose.glb",
    "elprimo/luchadorcorazon_win.glb",
    "elprimo/luchadordefault.glb",
    "elprimo/luchadordefault_lose.glb",
    "elprimo/luchadordefault_win.glb",
    "emz/mummydefault.glb",
    "emz/mummydefault_lose.glb",
    "emz/mummydefault_win.glb",
    "emz/mummydj.glb",
    "emz/mummydj_lose.glb",
    "emz/mummydj_win.glb",
    "eve/fleadefault.glb",
    "eve/fleadefault_lose.glb",
    "eve/fleadefault_win.glb",
    "fang/kickerdudedefault.glb",
    "fang/kickerdudedefault_lose.glb",
    "fang/kickerdudedefault_win.glb",
    "fang/kickerdudeocto.glb",
    "fang/kickerdudeocto_lose.glb",
    "fang/kickerdudeocto_win.glb",
    "frank/frankdefault.glb",
    "frank/frankdefault_lose.glb",
    "frank/frankdefault_win.glb",
    "frank/hammerdudedj.glb",
    "frank/hammerdudedj_lose.glb",
    "frank/hammerdudedj_win.glb",
    "frank/hammerdudeknight.glb",
    "frank/hammerdudeknight_lose.glb",
    "frank/hammerdudeknight_win.glb",
    "frank/hammerdudexmas.glb",
    "frank/hammerdudexmas_lose.glb",
    "frank/hammerdudexmas_win.glb",
    "gale/blowerdefault.glb",
    "gale/blowerdefault_lose.glb",
    "gale/blowerdefault_win.glb",
    "gene/hookdefault.glb",
    "gene/hookdefault_lose.glb",
    "gene/hookdefault_win.glb",
    "gray/doormandefault.glb",
    "gray/doormandefault_lose.glb",
    "gray/doormandefault_win.glb",
    "griff/assaultshotgundefault.glb",
    "grom/crossbomberdefault.glb",
    "grom/crossbomberdefault_lose.glb",
    "grom/crossbomberdefault_win.glb",
    "gus/soulcollectordefault.glb",
    "gus/soulcollectordefault_lose.glb",
    "gus/soulcollectordefault_win.glb",
    "hank/fishtankdefault.glb",
    "hank/fishtankdefault_lose.glb",
    "hank/fishtankdefault_win.glb",
    "jacky/drillerdefault.glb",
    "jacky/drillerdefault_lose.glb",
    "jacky/drillerdefault_win.glb",
    "janet/jetpackgirldefault.glb",
    "janet/jetpackgirldefault_lose.glb",
    "janet/jetpackgirldefault_win.glb",
    "janet/jetpackgirlpopstar.glb",
    "janet/jetpackgirlpopstar_lose.glb",
    "janet/jetpackgirlpopstar_win.glb",
    "janet/jetpackgirlvalkyrie.glb",
    "janet/jetpackgirlvalkyrie_lose.glb",
    "janet/jetpackgirlvalkyrie_win.glb",
    "jessie/mechanicdefault.glb",
    "jessie/mechanicdefault_lose.glb",
    "jessie/mechanicdefault_win.glb",
    "jessie/mechanicthief.glb",
    "leon/ninjadefault.glb",
    "leon/ninjaghost.glb",
    "lola/duplicatordefault.glb",
    "lola/duplicatordefault_lose.glb",
    "lola/duplicatordefault_win.glb",
    "lou/icedudedefault.glb",
    "lou/icedudedefault_lose.glb",
    "lou/icedudedefault_win.glb",
    "maisie/maisiedefault.glb",
    "maisie/maisiedefault_lose.glb",
    "maisie/maisiedefault_win.glb",
    "mandy/beamerdefault.glb",
    "mandy/beamerdefault_lose.glb",
    "mandy/beamerdefault_win.glb",
    "mandy/beamerlavaqueen.glb",
    "mandy/beamerlavaqueen_lose.glb",
    "mandy/beamerlavaqueen_win.glb",
    "mandy/beamermc.glb",
    "mandy/beamermc_lose.glb",
    "mandy/beamermc_win.glb",
    "max/speedydefault.glb",
    "max/speedydefault_lose.glb",
    "max/speedydefault_win.glb",
    "max/speedyleopard.glb",
    "max/speedyleopard_lose.glb",
    "max/speedyleopard_win.glb",
    "max/speedytracksuit.glb",
    "max/speedytracksuit_lose.glb",
    "max/speedytracksuit_win.glb",
    "meg/mechadudedefault.glb",
    "meg/mechadudedefault_lose.glb",
    "meg/mechadudedefault_win.glb",
    "meg/mechadudemonstertruck.glb",
    "meg/mechadudemonstertruck_lose.glb",
    "meg/mechadudemonstertruck_win.glb",
    "mortis/undertakerdefault.glb",
    "mortis/undertakerdefault_lose.glb",
    "mortis/undertakerdefault_win.glb",
    "mrp/spawnerdudedefault.glb",
    "mrp/spawnerdudedefault_lose.glb",
    "mrp/spawnerdudedefault_win.glb",
    "nani/controllerdefault.glb",
    "nani/controllerdefault_lose.glb",
    "nani/controllerdefault_win.glb",
    "nita/shamandefault.glb",
    "nita/shamandefault_lose.glb",
    "nita/shamandefault_win.glb",
    "otis/silencerdefault.glb",
    "otis/silencerdefault_lose.glb",
    "otis/silencerdefault_win.glb",
    "otis/silencerpharaoh.glb",
    "otis/silencerpharaoh_lose.glb",
    "otis/silencerpharaoh_win.glb",
    "pam/minigundudedefault.glb",
    "pam/minigundudedefault_lose.glb",
    "pam/minigundudedefault_win.glb",
    "pearl/cookerdefault.glb",
    "pearl/cookerdefault_lose.glb",
    "pearl/cookerdefault_win.glb",
    "penny/artillerygaldefault.glb",
    "penny/artillerygaldefault_lose.glb",
    "penny/artillerygaldefault_win.glb",
    "piper/sniperdefault.glb",
    "piper/sniperdefault_lose.glb",
    "piper/sniperdefault_win.glb",
    "piper/snipergold.glb",
    "piper/sniperline.glb",
    "piper/sniperline_lose.glb",
    "piper/sniperline_win.glb",
    "piper/snipermariposa.glb",
    "piper/snipermariposa_lose.glb",
    "piper/snipermariposa_win.glb",
    "piper/snipermoon.glb",
    "piper/snipermoon_lose.glb",
    "piper/snipermoon_win.glb",
    "piper/sniperpink.glb",
    "piper/sniperrose.glb",
    "piper/snipersilver.glb",
    "piper/snipervalentines.glb",
    "piper/snipervalentines_lose.glb",
    "piper/snipervalentines_win.glb",
    "poco/deadmariachidefault.glb",
    "poco/deadmariachidefault_lose.glb",
    "poco/deadmariachidefault_win.glb",
    "poco/deadmariachipunk.glb",
    "poco/deadmariachipunk_lose.glb",
    "poco/deadmariachipunk_win.glb",
    "rico/trickshotdefault.glb",
    "rico/trickshotdefault_lose.glb",
    "rico/trickshotdefault_win.glb",
    "rico/trickshotgold.glb",
    "rico/trickshotgold_lose.glb",
    "rico/trickshotgold_win.glb",
    "rosa/rosadefault.glb",
    "rosa/rosadefault_lose.glb",
    "rosa/rosadefault_win.glb",
    "rt/splitterdefault.glb",
    "rt/splitterdefault_lose.glb",
    "rt/splitterdefault_win.glb",
    "ruffs/ruffsdefault.glb",
    "ruffs/ruffsdefault_lose.glb",
    "ruffs/ruffsdefault_win.glb",
    "sam/weaponthrowerdefault.glb",
    "sam/weaponthrowerdefault_lose.glb",
    "sam/weaponthrowerdefault_win.glb",
    "sandy/sandstormdefault.glb",
    "sandy/sandstormdefault_lose.glb",
    "sandy/sandstormdefault_win.glb",
    "shelly/banditgirldefault.glb",
    "shelly/banditgirldefault_lose.glb",
    "shelly/banditgirldefault_win.glb",
    "spike/cactusdefault.glb",
    "spike/cactusdefault_lose.glb",
    "spike/cactusdefault_win.glb",
    "spike/cactuslog.glb",
    "spike/cactuslog_lose.glb",
    "spike/cactuslog_win.glb",
    "spike/cactuspink.glb",
    "sprout/wallydefault.glb",
    "sprout/wallydefault_lose.glb",
    "sprout/wallydefault_win.glb",
    "sprout/wallyweirdplant.glb",
    "sprout/wallyweirdplant_lose.glb",
    "sprout/wallyweirdplant_win.glb",
    "squeak/stickybombdefault.glb",
    "squeak/stickybombdefault_lose.glb",
    "squeak/stickybombdefault_win.glb",
    "stu/rollerdefault.glb",
    "stu/rollerdefault_lose.glb",
    "stu/rollerdefault_win.glb",
    "surge/powerlevelerdefault.glb",
    "surge/powerlevelerdefault_lose.glb",
    "surge/powerlevelerdefault_win.glb",
    "surge/powerlevelerkong.glb",
    "surge/powerlevelerkong_lose.glb",
    "surge/powerlevelerkong_win.glb",
    "tara/blackholedefault.glb",
    "tara/blackholedefault_lose.glb",
    "tara/blackholedefault_win.glb",
    "tara/blackholestreetninja.glb",
    "tara/blackholestreetninja_lose.glb",
    "tara/blackholestreetninja_win.glb",
    "tara/blackholeworldfinal.glb",
    "tara/blackholeworldfinal_lose.glb",
    "tara/blackholeworldfinal_win.glb",
    "tick/clusterbombdefault.glb",
    "tick/clusterbombdefault_lose.glb",
    "tick/clusterbombdefault_win.glb",
    "willow/puppeteerdefault.glb",
    "willow/puppeteerdefault_lose.glb",
    "willow/puppeteerdefault_win.glb"
]).map((value) => `models/${value}`));
